development:
  database:
    name: np_development
    host: 127.0.0.1
    port: 27017

test:
  database:
    name: np_test
    host: 127.0.0.1
    port: 27017

production:
  database:
    name: np
    host: 127.0.0.1
    port: 27017
